### ISSUE TITLE
Slow/Speedup

### ISSUE THREAD

**Issue by michelinok** [AndreasK79/dxcc-lookup#2]
Hi!
Is there a way to speedup the lookup?
Any ideas?
Many thanks for the great work!!!!!!!!!!!

**Comment by AndreasK79** [comment]
Hi. 

Can't say for sure. I never found it to be slow when testing myself. 
Did you implement this into a project of your own?

Do you do many lookups at a time? It reads the file each time, so that will slow it down some if you are determining the dxcc for many callsigns.

**Comment by michelinok** [comment]
Yes, I do massive lookup...
Any idea on how to avoid to read each time the file?
It's not a big problem...but if there's a way to avoid the multiple read it would be great!
Again...great work! I'll put credits to you in my website (it's a NO-PROFIT WEBSITE!!! it just manage an award of my clubstation)

**Comment by AndreasK79** [comment]
Then I understand the problem a little better. I'll take a look.

I have a few things that needs to be fixed at the same time. I'll let you know.

**Comment by michelinok** [comment]
Soooooooooooo many thanks!

**Comment by AndreasK79** [comment]
I pushed an update now. Should speedup things. Need to init class first (since consctructor reads cty-file) then run the lookup. Take a look in index.php how I did it. 

This made a big difference when testing locally. Please let me know how it goes.

**Comment by michelinok** [comment]
I'll try asap (tomorrow...I'm out of my qth till tomorrow) and let you
know!!!
Many thanks!

Mike iu5hes

Il giorno mer 22 mar 2023 alle ore 12:30 Andreas Kristiansen <
***@***.***> ha scritto:
