### ISSUE TITLE
Crash with a callsign

### ISSUE THREAD

**Issue by michelinok** [AndreasK79/dxcc-lookup#3]
Hi!
Can you check why this callsign crash the lookup?

UA6GO/MM

Trace

Warning: A non-numeric value encountered in C:\wamp64\theaward\dxcc\dxcc.php on line 39

**Comment by AndreasK79** [comment]
Hi.

I'll check it out.

**Comment by AndreasK79** [comment]
@michelinok I have pushed a fix now. The problem was that if the DXCC is none, it still tries to calculate bearing and distance.

**Comment by michelinok** [comment]
Thank you very much,really appreciated!
