### ISSUE TITLE
Cannot handle some callsigns

### ISSUE THREAD

**Issue by michelinok** [AndreasK79/dxcc-lookup#4]
Hi!
I'm testing your code againt my entire log and found that some calls are shown as "Unknown" but they exists.
This is a list of some callsign:

1U4UN (russia)
2R0BJL (england)
2K0CUH (england)
2K0GMK (england)
T96Q (Bosnia herzegovina)

If I can help, please let me know. Maybe they've forced theyr callsign/country on qrz.com ? This is just an idea.

**Comment by AndreasK79** [comment]
Hi.

1U4UN doesn't count for anything. See here: http://hamgallery.com/qsl/Unverified/1u4un.htm
As for the other calls, the CTY file does not contain information about those prefixes, so there is very little I can do about that.

**Comment by michelinok** [comment]
Thank you VERY MUCH for the fast answer!!!
Really appreciated your hints!

Mike
