### ISSUE TITLE
KL7SB - USA instead of Alaska

### ISSUE THREAD

**Issue by michelinok** [AndreasK79/dxcc-lookup#5]
Hi!
I've found that KL7SB returns USA instead of Alaska.
Is there a way to fix the code or the cty.dat (instrauctions needed) in some way?

Many thanks! Great work!

My best '73 de iu5hes op. Mike

**Comment by AndreasK79** [comment]
Hi Mike.

Yes, open cty.dat and remove KL7SB there. It is defined as USA, that is why this is happening.
